using Haiyu.Models;
using System.Text.Json.Serialization;
using Waves.Api.Models.CloudGame;

namespace Waves.Api.Models;

[JsonSerializable(typeof(CloudGameLoginData))]
[JsonSerializable(typeof(CloudApiResponse<CloudGameLoginData>))]
[JsonSerializable(typeof(CloudSendSMS))]
[JsonSerializable(typeof(AccessData))]
[JsonSerializable(typeof(CloudApiResponse<AccessData>))]
[JsonSerializable(typeof(PhoneTokenData))]
[JsonSerializable(typeof(CloudApiResponse<PhoneTokenData>))]
[JsonSerializable(typeof(CloudApiResponse<EndLoginData>))]
[JsonSerializable(typeof(CloudApiResponse<List<CloudGameNode>>))]
[JsonSerializable(typeof(CloudApiResponse<bool>))]
[JsonSerializable(typeof(CloudApiResponse<bool?>))]
[JsonSerializable(typeof(EndLoginData))]
[JsonSerializable(typeof(EndLoginRequest))]
[JsonSerializable(typeof(ExperienceCardInfo))]
[JsonSerializable(typeof(FreeTimeInfo))]
[JsonSerializable(typeof(HsstsToken))]
[JsonSerializable(typeof(PayTimeInfo))]
[JsonSerializable(typeof(EndLoginModel))]
[JsonSerializable(typeof(TimeCardInfo))]
[JsonSerializable(typeof(WalletData))]
[JsonSerializable(typeof(RecordModel))]
[JsonSerializable(typeof(RecordData))]
[JsonSerializable(typeof(RecardQuery))]
[JsonSerializable(typeof(WalletData))]
[JsonSerializable(typeof(CloudApiResponse<WalletData>))]
[JsonSerializable(typeof(CloudNetworkOrgin))]
[JsonSerializable(typeof(List<CloudNetworkOrgin>))]
[JsonSerializable(typeof(List<NodeList>))]
[JsonSerializable(typeof(KRSDK))]
[JsonSerializable(typeof(PKGData))]
[JsonSerializable(typeof(CloudBizData))]
[JsonSerializable(typeof(CommStartModel))]
[JsonSerializable(typeof(CloudApiResponse<CommStartReponse>))]
[JsonSerializable(typeof(CloudApiResponse<CommonQueueInfo>))]
[JsonSerializable(typeof(CloudApiResponse<RecordData>))]
[JsonSerializable(typeof(CloudBootstrapScript))]
[JsonSerializable(typeof(CloudGameAppStore))]
[JsonSerializable(typeof(CloudSdkLoginInfo))]
[JsonSerializable(typeof(CloudAppLoginInfo))]
[JsonSerializable(typeof(BridgeConfig))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(WelinkMessage))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(ApplyQualityProfilePayload))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
public partial class CloudGameContext : JsonSerializerContext { }
