using System.Collections.ObjectModel;
using System.Text.Json.Serialization;
using Waves.Api.Models.CloudGame;
using Waves.Api.Models.Communitys;
using Waves.Api.Models.Communitys.DataCenter;
using Waves.Api.Models.Communitys.DataCenter.ResourceBrief;

namespace Waves.Api.Models;

[JsonSerializable(typeof(AccountMine))]
[JsonSerializable(typeof(MineData))]
[JsonSerializable(typeof(Mine))]
[JsonSerializable(typeof(AccountModel))]
[JsonSerializable(typeof(SMSResultModel))]
[JsonSerializable(typeof(AccountData))]
[JsonSerializable(typeof(SMSResult))]
[JsonSerializable(typeof(GamerDataModel))]
[JsonSerializable(typeof(GameData))]
[JsonSerializable(typeof(EnergyData))]
[JsonSerializable(typeof(LivenessData))]
[JsonSerializable(typeof(ObservableCollection<BattlePassDataItem>))]
[JsonSerializable(typeof(GamerRoil))]
[JsonSerializable(typeof(GameRoilDataItem))]
[JsonSerializable(typeof(ChainList))]
[JsonSerializable(typeof(EquipPhantomList))]
[JsonSerializable(typeof(FetterDetail))]
[JsonSerializable(typeof(MainProp))]
[JsonSerializable(typeof(PhantomData))]
[JsonSerializable(typeof(PhantomProp))]
[JsonSerializable(typeof(Role))]
[JsonSerializable(typeof(ChallengeRole))]
[JsonSerializable(typeof(Detilys))]
[JsonSerializable(typeof(GamerChallengeDetily))]
[JsonSerializable(typeof(GamerRoilDetily))]
[JsonSerializable(typeof(Skill))]
[JsonSerializable(typeof(SkillList))]
[JsonSerializable(typeof(SubProp))]
[JsonSerializable(typeof(Weapon))]
[JsonSerializable(typeof(WeaponData))]
[JsonSerializable(typeof(PlayerCard))]
[JsonSerializable(typeof(PlayerReponse))]
[JsonSerializable(typeof(Datum))]
[JsonSerializable(typeof(SignIn))]
[JsonSerializable(typeof(SignInResult))]
[JsonSerializable(typeof(SignInData))]
[JsonSerializable(typeof(List<SignInGoodsConfigsItem>))]
[JsonSerializable(typeof(SignInGoodsConfigsItem))]
[JsonSerializable(typeof(DisposableGoodsListItem))]
[JsonSerializable(typeof(SignRecord))]
[JsonSerializable(typeof(BoxList))]
[JsonSerializable(typeof(TreasureBoxList))]
[JsonSerializable(typeof(GamerBassString))]
[JsonSerializable(typeof(GamerDataBool))]
[JsonSerializable(typeof(GamerBassData))]
[JsonSerializable(typeof(TreasureBoxList))]
[JsonSerializable(typeof(Phantom))]
[JsonSerializable(typeof(PhantomList))]
[JsonSerializable(typeof(GamerCalabashData))]
[JsonSerializable(typeof(ChallengeList))]
[JsonSerializable(typeof(IndexList))]
[JsonSerializable(typeof(GamerChallengeIndexData))]
[JsonSerializable(typeof(AreaInfoList))]
[JsonSerializable(typeof(Country))]
[JsonSerializable(typeof(DetectionInfoList))]
[JsonSerializable(typeof(ExploreList))]
[JsonSerializable(typeof(ItemList))]
[JsonSerializable(typeof(GamerExploreIndexData))]
[JsonSerializable(typeof(RoleList))]
[JsonSerializable(typeof(GamerRoleData))]
[JsonSerializable(typeof(DifficultyList))]
[JsonSerializable(typeof(FloorList))]
[JsonSerializable(typeof(TowerIndexRoleList))]
[JsonSerializable(typeof(GamerTowerIndexData))]
[JsonSerializable(typeof(TowerAreaList))]
[JsonSerializable(typeof(GamerTowerModel))]
[JsonSerializable(typeof(RoleSkinList))]
[JsonSerializable(typeof(GamerSkin))]
[JsonSerializable(typeof(WeaponSkinList))]
[JsonSerializable(typeof(GamerSlashDetailData))]
[JsonSerializable(typeof(HalfList))]
[JsonSerializable(typeof(SlashRoleList))]
[JsonSerializable(typeof(SlashDifficultyList))]
[JsonSerializable(typeof(SlashChallengeList))]
//资源简报
[JsonSerializable(typeof(BriefHeader))]
[JsonSerializable(typeof(BrieData))]
[JsonSerializable(typeof(BrieItem))]
[JsonSerializable(typeof(BrefListItem))]
[JsonSerializable(typeof(ResourceBrefItemData))]
[JsonSerializable(typeof(Recommend))]
[JsonSerializable(typeof(ResourceBrefItem))]
public partial class CommunityContext : JsonSerializerContext { }
